# Generated by Django 4.2.24 on 2026-03-16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fyle_accounting_mappings', '0031_fylesynctimestamp'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='expenseattribute',
            index=models.Index(fields=['workspace_id', 'attribute_type'], name='fyle_accoun_workspa_ea_idx'),
        ),
        migrations.AddIndex(
            model_name='destinationattribute',
            index=models.Index(fields=['workspace_id', 'attribute_type'], name='fyle_accoun_workspa_da_idx'),
        ),
        migrations.AddIndex(
            model_name='mapping',
            index=models.Index(fields=['workspace_id', 'source_type', 'destination_type'], name='fyle_accoun_workspa_mp_idx'),
        ),
        migrations.AddIndex(
            model_name='employeemapping',
            index=models.Index(fields=['workspace_id', 'source_employee_id'], name='fyle_accoun_workspa_em_idx'),
        ),
        migrations.AddIndex(
            model_name='categorymapping',
            index=models.Index(fields=['workspace_id', 'source_category_id'], name='fyle_accoun_workspa_cm_idx'),
        ),
    ]
