# Generated by Django 4.2.18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common_resources', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataMigrationBatch',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('object_ids', models.JSONField(default=list, help_text='Object IDs')),
                ('procedure_name', models.TextField(help_text='Procedure Name')),
                ('database_name', models.CharField(help_text='Database Name', max_length=100)),
                ('max_attempts', models.IntegerField(default=3, help_text='Max Attempts')),
                ('num_attempts', models.IntegerField(default=0, help_text='Number of Attempts')),
                ('started_at', models.DateTimeField(help_text='Started At', null=True)),
                ('completed_at', models.DateTimeField(help_text='Completed At', null=True)),
                ('failed_at', models.DateTimeField(help_text='Failed At', null=True)),
                ('error', models.JSONField(help_text='Error', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Updated At')),
            ],
            options={
                'db_table': 'data_migration_batches',
                'indexes': [
                    models.Index(
                        condition=models.Q(num_attempts=0, completed_at__isnull=True),
                        fields=['database_name', 'id'],
                        name='idx_dmb_unprocessed',
                    ),
                    models.Index(
                        condition=models.Q(completed_at__isnull=True, num_attempts__gt=0),
                        fields=['database_name', 'num_attempts', 'id'],
                        name='idx_dmb_retry',
                    ),
                ],
                'constraints': [
                    models.CheckConstraint(
                        check=models.Q(num_attempts__lte=models.F('max_attempts')),
                        name='num_attempts_lte_max_attempts',
                    ),
                    models.CheckConstraint(
                        check=models.Q(
                            models.Func(models.F('object_ids'), function='jsonb_array_length') <= 200
                        ),
                        name='object_ids_length_lte_200',
                    ),
                ],
            },
        ),
    ]
