# Generated by Django 4.2.29 on 2026-03-18 11:18

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common_resources', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataMigrationBatch',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('object_ids', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), help_text='Object IDs', size=None)),
                ('procedure_name', models.TextField(help_text='Procedure Name')),
                ('database_name', models.CharField(help_text='Database Name', max_length=100)),
                ('max_attempts', models.IntegerField(default=3, help_text='Max Attempts')),
                ('num_attempts', models.IntegerField(default=0, help_text='Number of Attempts')),
                ('started_at', models.DateTimeField(help_text='Started At', null=True)),
                ('completed_at', models.DateTimeField(help_text='Completed At', null=True)),
                ('failed_at', models.DateTimeField(help_text='Failed At', null=True)),
                ('error', models.JSONField(help_text='Error', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Updated At')),
            ],
            options={
                'db_table': 'data_migration_batches',
                'indexes': [models.Index(condition=models.Q(('completed_at__isnull', True), ('num_attempts', 0)), fields=['database_name', 'id'], name='idx_dmb_unprocessed'), models.Index(condition=models.Q(('completed_at__isnull', True), ('num_attempts__gt', 0)), fields=['database_name', 'num_attempts', 'id'], name='idx_dmb_retry')],
            },
        ),
        migrations.AddConstraint(
            model_name='datamigrationbatch',
            constraint=models.CheckConstraint(check=models.Q(('num_attempts__lte', models.F('max_attempts'))), name='num_attempts_lte_max_attempts'),
        ),
        migrations.AddConstraint(
            model_name='datamigrationbatch',
            constraint=models.CheckConstraint(check=models.Q(('object_ids__len__lte', 200)), name='object_ids_len_lte_200'),
        ),
    ]
