# Generated by Django 4.2.18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common_resources', '0002_datamigrationbatch'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='datamigrationbatch',
            index=models.Index(
                condition=models.Q(num_attempts=0, completed_at__isnull=True),
                fields=['database_name', 'id'],
                name='idx_dmb_unprocessed',
            ),
        ),
        migrations.AddIndex(
            model_name='datamigrationbatch',
            index=models.Index(
                condition=models.Q(completed_at__isnull=True, num_attempts__gt=0),
                fields=['database_name', 'num_attempts', 'id'],
                name='idx_dmb_retry',
            ),
        ),
    ]
